### PR TITLE
add VertexSlice Assns

### PR DESCRIPTION
**Pull request by wesketchum**
We are missing Vertex/Slice Assns in the dictionaries, which is something that microboone started making use of some time ago. Adding these in the in RecoBase/AssnsDicts area. Should be non-breaking...

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by yangtj207** [comment]
I was having troubling looking at a MCC9 file with the latest release because of the missing dictionaries. Thank you for fixing this issue Wes!

**Comment by tomjunk** [comment]
approved

**Comment by lgarren** [comment]
approve

**Pull request merged**
