### PR TITLE
Add sim::SimEnergyDepositLite, sim::MCMiniPart and g4trackID field

### PR DESCRIPTION
**Pull request by Temigo**
(Continuation of PR #30)

This PR is part of an effort from the ICARUS ML group to merge our pipeline back into the official production workflow.

* Create sim::SimEnergyDepositLite class, a lite version of sim::SimEnergyDeposit, with conversion to/from sim::SimEnergyDeposit
* Create sim::MCParticleLite (lite version of simb::MCParticle)
* Add `g4trackID` field to `sim::IDE` and `sim::SimEnergyDeposit`, to keep track of real track ID for EM shower daughters even when `KeepEMShowerDaughters: false` in LArG4.

**Caveat: I am not sure if the `ioread` rules I added for backwards compatibility are sufficient, because `sim::IDE` is not directly exposed (?) but tucked inside a `sim::SimChannel` object. Any advice or tip welcome!**

### CODE REVIEW

**Comment by lgarren** [comment]
@Temigo please fix the whitespace issues reported here https://github.com/LArSoft/lardataobj/pull/31#issuecomment-1253157039

**Comment by Temigo** [comment]
@lgarren I think the whitespace issue comes from deleting a file, not an actual whitespace issue? 
```
-bash-4.2$ curl -s -L https://patch-diff.githubusercontent.com/raw/LArSoft/lardataobj/pull/31.patch | grep '^diff --git ' | sed 's|.* a/||;s|  *b/.*||' | sort | uniq | tr '\n' ' ' > changed_files
-bash-4.2$ removeWhiteSpace.sh `cat changed_files`
sed: can't read lardataobj/MCBase/MCMiniPart.h: No such file or directory
```
I removed that file `lardataobj/MCBase/MCMiniPart.h` from the list of files in `changed_files`, since it was deleted in the PR. Then ran again:
```
-bash-4.2$ removeWhiteSpace.sh `cat changed_files`
-bash-4.2$ git status
On branch feature/ldomine_2trackID
Your branch is up to date with 'temigo/feature/ldomine_2trackID'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	changed_files

nothing added to commit but untracked files present (use "git add" to track)
-bash-4.2$
```
Nothing changed. I think that means there was no issue other than that missing `lardataobj/MCBase/MCMiniPart.h` ?

**Comment by lgarren** [comment]
@Temigo  lets see what happens when we provoke the code checks again.  A deleted file should not trigger the warning.

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
@Temigo The code check step is still failing.  I  will investigate.

**Comment by lgarren** [comment]
@Temigo  It appears that you are correct.  I have updated the code checks by hand and will open an issue to fix our whitespace script.

**Comment by Temigo** [comment]
Thanks @lgarren ! Can this PR move forward regardless or do we have to wait for the fix?

**Comment by lgarren** [comment]
@Temigo This PR can move forward if it is approved.  If I understand correctly, there is still an unresolved conversation with @knoepfel

**Comment by knoepfel** [comment]
@Temigo, at this point I'd say the changes are mostly fine.  The one open question is that there was a concern that the term `g4trackID` was somewhat confusing as `trackID` is also a G4 track ID.  So maybe `origTrackID` is better?  Or can you remember any of the other suggestions?

**Comment by Temigo** [comment]
@knoepfel I believed `g4trackID` was one of the suggestions made during the meeting to replace my old `groupID` naming. If you want me to rename it `origTrackID`, I can do that too I guess?

**Comment by knoepfel** [comment]
@Temigo, yes you are correct that `g4trackID` was a suggestion made at the meeting. @wesketchum then later suggested a different term (I think it was `origTrackID`) because of the potential confusion.  I'll let him comment further if he'd like to.

I believe we're mostly there--just this one issue I know of.

**Comment by Temigo** [comment]
Ok, my mistake then. Unless Wes comments in the next 15min, I'll start changing it to `origTrackID` and push the changes ASAP.

**Comment by Temigo** [comment]
@knoepfel Sorry for the wait, I wanted to make sure I wasn't breaking anything on my side = repeat basic tests. I changed `g4trackID` to `origTrackID` following your suggestion, in both `sim::IDE` and `sim::SimEnergyDeposit` (and corresponding places in LegacyLArG4).

**Comment by lgarren** [comment]
Thanks @Temigo 
@knoepfel code-checks approved manually per previous discussion.  See https://cdcvs.fnal.gov/redmine/issues/27410

**Comment by lgarren** [comment]
@Temigo These PRs need to be rebased against the head of develop.  Your PR overrides at least one important update.

**Comment by Temigo** [comment]
Ok @lgarren I can do that. Any chance that could be the source of the CI failures?

**Comment by lgarren** [comment]
@Temigo I was kind of hoping that might resolve the problem, but after more inspection I think not.

**Comment by knoepfel** [comment]
@Temigo, we have learned what the problem is with backwards compatibility.  Philippe Canal has identified a bug in ROOT that has created ROOT files without some of the necessary dictionary information for (e.g.) `sim::IDE` objects.  He has provided the SciSoft team with a potential workaround.  I will pursue that workaround and let you know if I have success and what the next steps will be.  Stay tuned.

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
@Temigo  We are trying to fix the whitespace code check issue, but apparently we haven't quite succeeded yet.

**Comment by knoepfel** [comment]
Closing in favor of PR #32, which includes a workaround for a bug in ROOT related to IO rules.

**Comment by knoepfel** [comment]
code-checks

**Comment by knoepfel** [comment]
code-checks

**Comment by greenc-FNAL** [comment]
code-checks

**Comment by greenc-FNAL** [comment]
code-checks

**Comment by greenc-FNAL** [comment]
code-checks

**Comment by greenc-FNAL** [comment]
code-checks

**Pull request closed without merging**
