### PR TITLE
Create a new data product recob::OpWaveform to save calibrated photon detector waveforms.

### PR DESCRIPTION
**Pull request by yangtj207**
Create a new data product recob::OpWaveform to save calibrated photon detector waveforms following the design of recob::Wire. This was requested by Rodrigo Alvarez Garrote:
https://indico.fnal.gov/event/54181/contributions/239542/attachments/154185/200235/LArSoft_OpWaveform_PR.pdf

### CODE REVIEW

**Comment by yangtj207** [comment]
trigger build

**Comment by yangtj207** [comment]
trigger build

**Comment by knoepfel** [comment]
Looks good, @yangtj207.  Will approve once we have L2 approval.

**Comment by lgarren** [comment]
@LArSoft/level-2-managers Please approve or comment

**Comment by tomjunk** [comment]
Approved.  The name OpWaveform is a bit similar to OpDetWaveform however, but it is no worse than recob::Wire, and the "Det" part at least is a hint that it comes directly from the detector.

**Comment by lgarren** [comment]
approve

**Pull request merged**
