### PR TITLE
Modification to add ROISummedADC and HitSummedADC

### PR DESCRIPTION
**Pull request by amerega**
Commit related to the LArSoft meeting 
https://indico.fnal.gov/event/64331/
This commit is related to 3 parallel requests in: larreco, lardata and lardataobj

!! For the experts please have a look at line 223 of test/RecoBase/Hit_test.cc

### CODE REVIEW

**Comment by knoepfel** [comment]
code-checks

**Comment by SFBayLaser** [comment]
I am nervous about changing the name from "HitSummedADC" to "ROISummedADC" since so much analysis code (including private code not in repositories that could be updated easily) used the current name. I  should also point out that it is not the sum over the input ROI necessarily, but is the sum over ADC values in a "snippet" which can be a subset of an ROI.

**Comment by amerega** [comment]
Just to be clear HitSummedADC was not moved to ROISummedADC.

- SummedADC was transformed into ROISummedADC
- HitSummedADC was added as new variable

I thought that that was agreed on at the latest larsoft meeting.

Regards
Anselmo


Il giorno 22 apr 2024, alle ore 18:40, Tracy Usher ***@***.***> ha scritto:



I am nervous about changing the name from "HitSummedADC" to "ROISummedADC" since so much analysis code (including private code not in repositories that could be updated easily) used the current name. I should also point out that it is not the sum over the input ROI necessarily, but is the sum over ADC values in a "snippet" which can be a subset of an ROI.

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
@amerega please fix the code formatting as requested on these 3 PRs.

**Comment by amerega** [comment]
Dear all, is there anything blocking my pull request? If not when will it be treated? Thanks in advance

**Comment by lgarren** [comment]
trigger build with pull requests #42, LArSoft/lardata#34, LArSoft/lareventdisplay#24, LArSoft/larreco#64, LArSoft/larrecodnn#46

**Comment by tomjunk** [comment]
This did break a DUNE CI build where SummedADC() should be changed to ROISummedADC().  From the build log:

/scratch/workspace/dune_ci/label_exp/swarm/label_exp2/swarm/DUNE/srcs/duneprototypes/duneprototypes/Protodune/dualphase/AnaRootParser_module.cc
23081: /scratch/workspace/dune_ci/label_exp/swarm/label_exp2/swarm/DUNE/srcs/duneprototypes/duneprototypes/Protodune/dualphase/AnaRootParser_module.cc: In member function 'virtual void dune::AnaRootParser::analyze(const art::Event&)':
23082: /scratch/workspace/dune_ci/label_exp/swarm/label_exp2/swarm/DUNE/srcs/duneprototypes/duneprototypes/Protodune/dualphase/AnaRootParser_module.cc:4718:44: error: 'const class recob::Hit' has no member named 'SummedADC'; did you mean 'ROISummedADC'?
23083:  4718 |     fData->hit_chargesum[i]  = hitlist[i]->SummedADC();
23084:       |                                            ^~~~~~~~~
23085:       |                                            ROISummedADC
23086: /scratch/workspace/dune_ci/label_exp/swarm/label_exp2/swarm/DUNE/srcs/duneprototypes/duneprototypes/Protodune/dualphase/AnaRootParser_module.cc:5567:66: error: 'const class recob::Hit' has no member named 'SummedADC'; did you mean 'ROISummedADC'?
23087:  5567 |             TrackerData.hittrkchargesum[HitIterator2] = vhit[h]->SummedADC();
23088:       |                                                                  ^~~~~~~~~
23089:       |                                                                  ROISummedADC

**Comment by lgarren** [comment]
trigger build with pull requests #42, LArSoft/lardata#34, LArSoft/lareventdisplay#24, LArSoft/larreco#64, LArSoft/larrecodnn#46, DUNE/dunedataprep#35, DUNE/duneprototypes#58, DUNE/dunereco#113, DUNE/protoduneana#35, DUNE/duneana#75

**Comment by tomjunk** [comment]
It's not impossible to update the DUNE code I see about 21 non-commented-out instances of hit::SummedADC() in the DUNE code.

**Comment by lgarren** [comment]
@tomjunk There are already PRs for DUNE.  I just resubmitted the build.

**Comment by tomjunk** [comment]
Oh, I see Lynn has already made the PRs.

**Comment by tomjunk** [comment]
Thanks!  :)

**Comment by lgarren** [comment]
@tomjunk The PRs were made by the author.  To my knowledge, the other experiments have not yet received similar treatment.

**Comment by tomjunk** [comment]
Something's wrong with the DUNE test on these PRs that may be unrelated to the PRs:

https://dbweb8.fnal.gov:8443/LarCI/app/ns:dune/storage/docs/2024/09/04/stderr%23oGlErZF.log

Looks like Pandora libraries aren't being found in CVMFS.  I did try ls'ing one of them on a dunegpvm and found it however.

**Comment by tomjunk** [comment]
Oh, the libraries like the shower creation library can be found, but libLArPandoraContent cannot.

26:     Unable to load requested library /cvmfs/larsoft-ib.opensciencegrid.org/LArSoft/LArSoft_custom_slf7_e26_prof_20240904_172646/localProducts_LArSoft_LArSoft_lar_ci_e26_prof/larpandora/v09_22_11/slf7.x86_64.e26.prof/lib/liblarpandora_LArPandoraEventBuilding_LArPandoraShower_LArPandoraShowerCreation_module.so
27:     libLArPandoraContent.so.04.10: cannot open shared object file: No such file or directory

A manually triggered DUNE CI test worked yesterday however.

**Comment by lgarren** [comment]
Sorry, this is my fault.  There is a disconnect between the head of develop of larpandoracontent and what is installed on cvmfs.  Will make a small new release soon.

**Comment by lgarren** [comment]
trigger build with pull requests #42, LArSoft/lardata#34, LArSoft/lareventdisplay#24, LArSoft/larreco#64, LArSoft/larrecodnn#46, DUNE/dunedataprep#35, DUNE/duneprototypes#58, DUNE/dunereco#113, DUNE/protoduneana#35, DUNE/duneana#75

**Comment by lgarren** [comment]
@tomjunk please take another look

**Comment by tomjunk** [comment]
@lgarren My apologies for being slow here -- two weeklong meetings this week piled up on top of one another.  Looks like the CI tests succeeded with DUNE's PRs.  I'm okay with this.

**Comment by lgarren** [comment]
approve

**Pull request merged**
