### PR TITLE
Feature/tjyang opwaveform

### PR DESCRIPTION
**Pull request by yangtj207**
Change time stamp of recob::OpWaveform from raw::RDTimeStamp to double to be consistent with raw::OpDetWaveform.

### CODE REVIEW

**Comment by yangtj207** [comment]
trigger build

**Comment by absolution1** [comment]
approve

**Comment by knoepfel** [comment]
@yangtj207, because the new type `double` is not a type alias/typedef for `raw::RDTimestamp`, there will need to be an I/O rule for this conversion to support older files.  Have you looked at how to create the I/O rule?  Or do you have other plans for effecting the migration?  Perhaps adding a data member that encodes the timestamp as a `double` makes more sense.

**Comment by yangtj207** [comment]
Hi @knoepfel, this data product is relatively new and has not been used by any productions or people except me doing some tests. Would it be OK to skip the I/O rule for now? Thanks.

**Comment by yangtj207** [comment]
@knoepfel I just added an IO rule. Hopefully it addresses the backward compatibility concern.

**Comment by knoepfel** [comment]
Thanks, @yangtj207.  I have a question: is the timestamp always given in integer values?  I see code like https://github.com/DUNE/duneopdet/blob/develop/duneopdet/OpticalDetector/Deconvolution/Deconvolution_module.cc#L560-L561:

```.cpp
recob::OpWaveform decwav(wf.TimeStamp(), wf.ChannelNumber(), out_recob_float );
out_recob->emplace_back(std::move(decwav));
```

where `wf.TimeStamp()` returns a `double`, which is implicitly converted to a `RDTimeStamp` when the `OpWaveform` is constructed.  I would think that any digits after the decimal point would be lost whenever the `RDTimeStamp` is constructed.  Is that a problem?

**Comment by yangtj207** [comment]
> Thanks, @yangtj207. I have a question: is the timestamp always given in integer values? I see code like https://github.com/DUNE/duneopdet/blob/develop/duneopdet/OpticalDetector/Deconvolution/Deconvolution_module.cc#L560-L561:
> 
> ```c++
> recob::OpWaveform decwav(wf.TimeStamp(), wf.ChannelNumber(), out_recob_float );
> out_recob->emplace_back(std::move(decwav));
> ```
> 
> where `wf.TimeStamp()` returns a `double`, which is implicitly converted to a `RDTimeStamp` when the `OpWaveform` is constructed. I would think that any digits after the decimal point would be lost whenever the `RDTimeStamp` is constructed. Is that a problem?

Thanks @knoepfel. You are right about the loss of information when converting RDTimeStamp to double. That's the reason for this PR. After the PR is merged, the time stamp information will be properly saved.

**Comment by knoepfel** [comment]
trigger build

**Comment by knoepfel** [comment]
Thanks, @yangtj207.  I'm happy with this PR now.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
