### PR TITLE
Extended `recob::SpacePoint` interface.

### PR DESCRIPTION
**Pull request by PetrilloAtWork**

### CODE REVIEW

**Review by knoepfel — COMMENTED** [review]
Nicely done, Gianluca.  Will approve after L2 approval.

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
CI test results are normal

**Comment by tomjunk** [comment]
Approved

To consider:  check the arguments of Covariance(i,j) for validity.  Emit error message if i and j are too big.  Sometimes I prefer a segfault to a thrown exception in cases like this, as a debugger can catch it better than an unwound stack.  People putting in invalid i and j deserve what they get but a message might be nice.

**Comment by lgarren** [comment]
@PetrilloAtWork  Tom made some interesting sugggestions.  Do you want to pursue them before this PR is finalized?

**Comment by SFBayLaser** [comment]
To my knowledge the "error matrix" is never filled... and because of that some entrepreneurial types have usurped the space for other purposes. So... implementing a test will require code rewrites in some places. Obviously, the "right way" to handle the alternate usage of the error matrix is to include meta data with each space point... but at this point this also requires code rewrites. So I might suggest putting this on a future to do list and first ferret out the alternate usages (in LArReco and LArEventDisplay).

**Comment by lgarren** [comment]
@SFBayLaser  I believe Tom is referring to SpacePoint::covariance, which is new in this PR.

**Comment by tomjunk** [comment]
I was proposing something simple

constexpr std::size_t SpacePoint::covIndex(unsigned int i, unsigned int j) {

    constexpr std::size_t offsets[3U] = { 0U, 1U, 3U };

// proposed change:

   if (i>2U || j>2U)
{
  MF_LOG_ERROR("SpacePoint::covindex") << "Bad index: " << i << j;
  throw exception (though backtrace is preferred).
}
// end proposed change
    if (i < j) std::swap(i, j);
    return offsets[i] + j;

  } // SpacePoint::covIndex()

**Comment by lgarren** [comment]
This PR is going in now.  Any further changes should come in a new PR.

**Comment by lgarren** [comment]
approve

**Pull request merged**
